"use strict";
export const TIMELINEITEMS_REQUEST = "TIMELINEITEMS_REQUEST";
export const TIMELINEITEMS_RECEIVED = "TIMELINEITEMS_RECEIVED";
export const TIMELINEITEMS_FAILURE = "TIMELINEITEMS_FAILURE";
export const FILTERCRITERIA_UPDATE = "FILTERCRITERIA_UPDATE";